apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {% .component_name %}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.{% .main_object_block %}.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.{% .main_object_block %}.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.{% .main_object_block %}.service.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.{% .main_object_block %}.service.type }}
  {{- if and .Values.{% .main_object_block %}.service.clusterIP (eq .Values.{% .main_object_block %}.service.type "ClusterIP") }}
  clusterIP: {{ .Values.{% .main_object_block %}.service.clusterIP }}
  {{- end }}
  {{- if .Values.{% .main_object_block %}.service.sessionAffinity }}
  sessionAffinity: {{ .Values.{% .main_object_block %}.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.{% .main_object_block %}.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.{% .main_object_block %}.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.{% .main_object_block %}.service.type "LoadBalancer") (eq .Values.{% .main_object_block %}.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.{% .main_object_block %}.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.{% .main_object_block %}.service.type "LoadBalancer") (not (empty .Values.{% .main_object_block %}.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.{% .main_object_block %}.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.{% .main_object_block %}.service.type "LoadBalancer") (not (empty .Values.{% .main_object_block %}.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.{% .main_object_block %}.service.loadBalancerIP }}
  {{- end }}
  ports:
    {%- $main_object_block := .main_object_block -%}
    {%- range $key, $value := .ports %}
    - name: {% $value.name %}
      port: {{ .Values.{% $main_object_block %}.service.ports.{% $value.name %} }}
      protocol: {% default "TCP" $value.protocol %}
      {{- if and (or (eq .Values.{% $main_object_block %}.service.type "NodePort") (eq .Values.{% $main_object_block %}.service.type "LoadBalancer")) (not (empty .Values.{% $main_object_block %}.service.nodePorts.http)) }}
      nodePort: {{ .Values.{% $main_object_block %}.service.nodePorts.http }}
      {{- else if eq .Values.{% $main_object_block %}.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {%- end %}
    {{- if .Values.{% .main_object_block %}.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.{% .main_object_block %}.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: {% .component_name %}
